# Optimización del costo para la asignación de profesores (premium)

**Problema de asignación**: ECs baratos y con disponibilidad no están quedando asignados. 
**Solución y otras incorporaciones**: 
1. Hacer una asignación por capas, para garantizar que ningun EC costoso le quite series a un EC barato. 
2. Randomizar la selección cuando tienen el mismo fee
3. Glenda (email g.vega@slangapp.com) es la única retainer y toca contenerla en 80-90h mensuales. (esto quisiera hacerlo modificandole el fee para no cambiar mucho la logica del cogido)

### Importamos paquetes

In [728]:
# si es la primera vez que se ejecuta, tenemos que instalar PuLP usando la terminal
# utilice este comando:
# pip install pulp
import pandas as pd
import numpy as np
import random
import numpy as np
import matplotlib.pyplot as plt
from statistics import mode, StatisticsError
from datetime import datetime, timedelta

In [729]:
# si queremos quitar warnings mamones!
import warnings

# Suppress all FutureWarnings
warnings.simplefilter(action='ignore', category=FutureWarning)

### Creamos funciones auxiliares

In [730]:
# Estas están pensadas ejecutar solo dentro de la función main

def series_sin_prof_princ(df, series, probabilidad_ppppp):
    series_sin_prof_princ = 0
    for s in series:
        df_s = df[df['Series ID'] == s]
        if len(df_s) == 0:
            # print("Serie sin asignaciones: ", s)
            continue
        else:
            prof_princ = profesor_principal(df, s)
            mode_length = len(df_s[df_s['Teacher Assigned'] == prof_princ] )
            len_dfs = len(df_s)
            percentage = str(round(100*mode_length/len_dfs,2)) + "%"
            if mode_length/len_dfs < probabilidad_ppppp:
                # print(df_s)
                series_sin_prof_princ += 1
    return series_sin_prof_princ



def total_profesores_asignados(df, series, momentos):
    profesores_utilizados = []
    for s in series:
        for i in momentos:
            clase =  df[(df['Series ID'] == s) & (df['Moment ID'] == i)]
            if len(clase) == 0:
                # print("Serie sin asignaciones: ", s)
                continue
            else:
                profesores_utilizados.append(list(df[(df['Series ID'] == s) & (df['Moment ID'] == i)]['Teacher Assigned'])[0])
    
    return len(np.unique(profesores_utilizados))


# Function to generate classes for each series
def generate_classes(series_df, start_date):
    class_rows = []
    class_id = 1
    
    for idx, row in series_df.iterrows():
        series_name = row['Series Name']
        day1 = row['Day 1']
        day2 = row['Day 2']
        time1 = int(row['Time 1'])
        time2 = int(row['Time 2'])
        series_level = row['Level Number']
        
        # Create 16 classes (8 weeks, 2 per week)
        for week in range(8):
            # Calculate the date for Day 1 of this series in this week
            day1_date = start_date + timedelta(days=(day1 - 1) + week * 7)
            class_rows.append({
                'Class ID': f'C{class_id}',
                'Series ID': series_name,
                'Series Level': series_level,
                'Starts At': datetime(day1_date.year, day1_date.month, day1_date.day, time1)
            })
            class_id += 1
            
            # Calculate the date for Day 2 of this series in this week
            day2_date = start_date + timedelta(days=(day2 - 1) + week * 7)
            class_rows.append({
                'Class ID': f'C{class_id}',
                'Series ID': series_name,
                'Series Level': series_level,
                'Starts At': datetime(day2_date.year, day2_date.month, day2_date.day, time2)
            })
            class_id += 1
    
    return pd.DataFrame(class_rows)





# Function to generate classes for each series
def generate_classes2(series_df, start_date):
    class_rows = []
    class_id = 1
    
    for idx, row in series_df.iterrows():
        series_name = row['Series Name']
        day1 = row['Day 1']
        day2 = row['Day 2']
        time = int(row['Time'])
        teacher_assigned = row['Teacher Assigned']
        
        # Create 16 classes (8 weeks, 2 per week)
        for week in range(8):
            # Calculate the date for Day 1 of this series in this week
            day1_date = start_date + timedelta(days=(day1 - 1) + week * 7)
            class_rows.append({
                'Class ID': f'C{class_id}',
                'Series ID': series_name,
                'Teacher Assigned': teacher_assigned,
                'Starts At': datetime(day1_date.year, day1_date.month, day1_date.day, time)
            })
            class_id += 1
            
            # Calculate the date for Day 2 of this series in this week
            day2_date = start_date + timedelta(days=(day2 - 1) + week * 7)
            class_rows.append({
                'Class ID': f'C{class_id}',
                'Series ID': series_name,
                'Teacher Assigned': teacher_assigned,
                'Starts At': datetime(day2_date.year, day2_date.month, day2_date.day, time)
            })
            class_id += 1
    
    return pd.DataFrame(class_rows)

### Función main()

In [731]:
def main(series_df, start_date, teacher_availability, teacher_info, min_availability, capa_dolares):

    classes = generate_classes(series_df, start_date)


    ## creamos vectores/variables (profesores j, momentos i, series s)
    teachers = list(teacher_info['teacher_email'].unique())
    N = len(teachers)
    momentos_timestamp = sorted(list(classes['Starts At'].unique()))
    momentos_int = list(range(1, len(momentos_timestamp) + 1))
    momentos = [str(i) for i in momentos_int]
    # Create a dictionary mapping the ID vector to the elements of M
    diccionario_momentos = {momentos[i]: momentos_timestamp[i] for i in range(len(momentos_timestamp))}
    X_c = len(momentos)
    series = list(classes['Series ID'].unique())
    Y = len(series)
    print("Tenemos ", N, " profesores disponibles para la asignación")
    print("Tenemos ", X_c, " momentos con una o mas clases")
    print("Tenemos ", Y, " series que tenemos que asignar")

    ## Transformamos la información de costos de profesores ajustado a la matriz de disponibilidad (si no tiene disponibilidad no voy a revisar su costo)
    teacher_info['fee'] = pd.to_numeric(teacher_info['fee'], errors='coerce')
    teacher_costs = pd.DataFrame(index = teachers)
    teacher_costs['fee'] = 0
    teacher_costs['Total series'] = 0
    teacher_costs['Overachiever'] = False
    for j in teachers:
        if j in list(teacher_info['teacher_email']):
            w = teacher_info[teacher_info['teacher_email'] == j]['fee'].values[0]
            t = teacher_info[teacher_info['teacher_email'] == j]['Total series'].values[0]
            x = teacher_info[teacher_info['teacher_email'] == j]['Max series'].values[0]
            k = teacher_info[teacher_info['teacher_email'] == j]['Overachiever'].values[0]
            teacher_costs.loc[j, 'fee'] = w
            teacher_costs.loc[j, 'Total series'] = t
            teacher_costs.loc[j, 'Max series'] = x
            teacher_costs.loc[j, 'Overachiever'] = k

        # if k == True:
        #     teacher_costs.loc[j, 'fee'] = overachiever_fee

    # transformamos la información de profesores para tener una tabla de los niveles que pueden dictar


    ## A partir de tabla de horas libres de cada profesor (treacher_availability) creamos la matriz de disponibilidad, con el vector de momentos y profesores
    A = np.zeros((X_c, N))
    A = pd.DataFrame(A, index = momentos, columns = teachers)
    for j in teachers:
        for i in momentos:
            filtered_df = teacher_availability[(teacher_availability['slot_time'] == diccionario_momentos[i]) & (teacher_availability['teacher_email'] == j)]
            if not filtered_df.empty:
                A[j][i] = 1



    ## A partir de tabla de clases (classes) creamos la matriz de horarios a dictar, con el vector de series y momentos
    B = np.zeros((Y, X_c))
    B = pd.DataFrame(B, index = series, columns = momentos)
    for s in series:
        for i in momentos:
            filtered_df_2 = classes[(classes['Starts At'] == diccionario_momentos[i]) & (classes['Series ID'] == s)]
            if not filtered_df_2.empty:
                B[i][s] = 1


    ## A partir de tabla descriptiva de profesores (teacher info) y la tabla de series creamos la matriz de series que puede o no dictar cada profesor
    C = np.zeros((Y, N))
    C = pd.DataFrame(B, index = series, columns = teachers)
    for s in series:
        series_level = ((series_df[series_df['Series Name'] == s])['Level Number']).iloc[0]
        level_name = 'Level ' + str(int(series_level))
        for j in teachers:
            filtered_df_3 = (teacher_info[(teacher_info['teacher_email'] == j)][level_name])
            if not filtered_df_3.empty:
                C[j][s] = filtered_df_3

    #calculamos cantidad de clases a asignar y horas disponibles mediante las matrices. 
    total_classes_ = B.sum().sum()
    total_disponibilidad = A.sum().sum()
    suma_C = C.sum().sum()

    # Primer print para definir el status de la ejecución: comprension general del problema. Estos numeros deben coincidir con el numero de filas que tienen los inputs correspondientes
    print("Hay un total de ", total_classes_, "clases a asignar")
    print("Hay un total de ", total_disponibilidad, "horas disponibles de profesores")
    print("Hay un total de ", suma_C, "disponibilidades por nivel")
    

    # assign teachers

    assigned = []
    unassigned = []
    num = 0
    
    df = teacher_costs.copy()
    df = df.sample(frac=1)
    
    min_fee = df["fee"].min()
    max_fee = df["fee"].max()

    # Build buckets bottom-up (LOWEST fee first)
    bins = np.arange(
        start=min_fee,
        stop=max_fee + capa_dolares,
        step=capa_dolares
    )

    asignaciones = 0
    capa = 1

    for lower in bins:
        print("Capa #" + str(capa))
        capa = capa + 1
        upper = lower + capa_dolares

        temp_df = df[
            (df["fee"] >= lower) &
            (df["fee"] < upper)
        ]

        if temp_df.empty:
            continue
        
        assigned_series = set()
        
        temp_df = temp_df.sample(frac=1)
        
        # print(temp_df)

        
        for s in series:
            # Find teachers available for at least X% of the classes in the series
            available_teachers = []
            total_classes = B.loc[s, :].sum()

            for j in temp_df.index:
                availability_count = sum(int(A.loc[i, j]) * int(B.loc[s, i]) for i in A.index) 
                
                if (availability_count >= min_availability * total_classes) and (C.loc[s, j] == 1) and (temp_df.loc[j, "Total series"] < temp_df.loc[j, "Max series"]):
                    available_teachers.append((j, temp_df.loc[j, "fee"], availability_count))

            if len(available_teachers) > 0:
                asignaciones = asignaciones + 1 
                print(str(asignaciones) + " ass")
                # Find the least expensive teacher
                random.shuffle(available_teachers)
                available_teachers.sort(key=lambda x: x[1])
                selected_teacher = available_teachers[0][0]
                teacher_cost = available_teachers[0][1]
                current_series = df.loc[selected_teacher, 'Total series']
                # Assign the teacher to the available classes
                for i in momentos:
                    if B.loc[s, i] == 1 and A.loc[i, selected_teacher] == 1:
                        assigned.append({"Series ID": s, "Moment ID": i, "Teacher": selected_teacher, "Cost": teacher_cost})
                        A.loc[i, selected_teacher] = 0
                        assigned_series.add(s) 
                        df.loc[selected_teacher, 'Total series'] = current_series + 1
                        temp_df.loc[selected_teacher, 'Total series'] = current_series + 1
                    else:
                        unassigned.append({"Series ID": s, "Moment ID": i})
        
        print(assigned_series)
        series = [s for s in series if s not in assigned_series]

        if not series: # revisamos si está vacía para parar el ciclo
            print("No hay mas series por asignar")
            break

    

    # Convert assignments to DataFrames
    assigned_df = pd.DataFrame(assigned)
    unassigned_df = pd.DataFrame(unassigned)


    print("Solución encontrada. Ahora se va validara la utilidad del resultado!")
    return assigned_df, unassigned_df, df

### Evaluacion de resultados

In [732]:
def evaluate_solution(assigned_df, series_df, start_date, teacher_availability, teacher_info):
    """
    Evaluates the solution found in assigned_df based on the following conditions:
    1. Teachers were assigned taking into account their original availability.
    2. Teachers are not assigned to two or more classes that occur at the same moment.
    3. Only one teacher per class.
    4. Teachers were assigned to classes according to their level.
    5. We are not assigning teachers to non-existing classes.
    
    Parameters:
    - assigned_df: DataFrame with the assigned classes to teachers.
    - A: Original availability matrix (moments x teachers).
    - B: Original series schedule matrix (series x moments).
    - C: Original teacher suitability matrix (series x teachers).
    
    Returns:
    - evaluation_results: Dictionary containing DataFrames with classes that do not meet each condition.
    """

    classes = generate_classes(series_df, start_date)


    ## creamos vectores/variables (profesores j, momentos i, series s)
    teachers = list(teacher_info['teacher_email'].unique())
    N = len(teachers)
    momentos_timestamp = sorted(list(classes['Starts At'].unique()))
    momentos_int = list(range(1, len(momentos_timestamp) + 1))
    momentos = [str(i) for i in momentos_int]
    # Create a dictionary mapping the ID vector to the elements of M
    diccionario_momentos = {momentos[i]: momentos_timestamp[i] for i in range(len(momentos_timestamp))}
    X_c = len(momentos)
    series = list(classes['Series ID'].unique())
    Y = len(series)


    ## Transformamos la información de costos de profesores ajustado a la matriz de disponibilidad (si no tiene disponibilidad no voy a revisar su costo)
    teacher_info['fee'] = pd.to_numeric(teacher_info['fee'], errors='coerce')
    teacher_costs = pd.DataFrame(index = teachers)
    teacher_costs['fee'] = 0
    for j in teachers:
        if j in list(teacher_info['teacher_email']):
            w = teacher_info[teacher_info['teacher_email'] == j]['fee'].values[0]
            teacher_costs.loc[j] = w

    # transformamos la información de profesores para tener una tabla de los niveles que pueden dictar


    ## A partir de tabla de horas libres de cada profesor (treacher_availability) creamos la matriz de disponibilidad, con el vector de momentos y profesores
    A = np.zeros((X_c, N))
    A = pd.DataFrame(A, index = momentos, columns = teachers)
    for j in teachers:
        for i in momentos:
            filtered_df = teacher_availability[(teacher_availability['slot_time'] == diccionario_momentos[i]) & (teacher_availability['teacher_email'] == j)]
            if not filtered_df.empty:
                print(1)
                A[j][i] = 1


    ## A partir de tabla de clases (classes) creamos la matriz de horarios a dictar, con el vector de series y momentos
    B = np.zeros((Y, X_c))
    B = pd.DataFrame(B, index = series, columns = momentos)
    for s in series:
        for i in momentos:
            filtered_df_2 = classes[(classes['Starts At'] == diccionario_momentos[i]) & (classes['Series ID'] == s)]
            if not filtered_df_2.empty:
                B[i][s] = 1


    ## A partir de tabla descriptiva de profesores (teacher info) y la tabla de series creamos la matriz de series que puede o no dictar cada profesor
    C = np.zeros((Y, N))
    C = pd.DataFrame(B, index = series, columns = teachers)
    for s in series:
        series_level = ((series_df[series_df['Series Name'] == s])['Level Number']).iloc[0]
        level_name = 'Level ' + str(series_level)
        for j in teachers:
            filtered_df_3 = (teacher_info[(teacher_info['teacher_email'] == j)][level_name])
            if not filtered_df_3.empty:
                C[j][s] = filtered_df_3
    
    # 1. Teachers were assigned taking into account their original availability
    availability_issues = assigned_df[
        assigned_df.apply(lambda row: A.loc[row['Moment ID'], row['Teacher']] != 1, axis=1)
    ]
    
    # 2. Teachers are not assigned to two or more classes that occur at the same moment
    simultaneous_issues = assigned_df.groupby(['Moment ID', 'Teacher']).filter(lambda x: len(x) > 1)
    
    # 3. Only one teacher per class
    unique_teacher_issues = assigned_df.groupby(['Series ID', 'Moment ID']).filter(lambda x: len(x) > 1)
    
    # 4. Teachers were assigned to classes according to their level
    level_issues = assigned_df[
        assigned_df.apply(lambda row: C.loc[row['Series ID'], row['Teacher']] != 1, axis=1)
    ]
    
    # 5. We are not assigning teachers to non-existing classes
    non_existing_classes_issues = assigned_df[
        assigned_df.apply(lambda row: B.loc[row['Series ID'], row['Moment ID']] != 1, axis=1)
    ]

    evaluation_results = {
        "Availability_Issues": availability_issues,
        "Simultaneous_Issues": simultaneous_issues,
        "Unique_Teacher_Issues": unique_teacher_issues,
        "Level_Issues": level_issues,
        "Non_Existing_Classes_Issues": non_existing_classes_issues
    }
    
    return evaluation_results

In [733]:
def calculate_main_teacher_assistance(assigned_df):
    # Count the number of classes each teacher is assigned to in each series
    series_teacher_counts = (
        assigned_df.groupby(['Series ID', 'Teacher'])
        .size()
        .reset_index(name='Assigned Classes Count')
    )
    
    # Find the main teacher for each series (teacher with the most classes)
    main_teachers = (
        series_teacher_counts.loc[series_teacher_counts.groupby('Series ID')['Assigned Classes Count'].idxmax()]
        .reset_index(drop=True)
    )
    
    # Calculate the percentage of classes the main teacher is assigned to
    total_classes_per_series = assigned_df['Series ID'].value_counts().reset_index()
    total_classes_per_series.columns = ['Series ID', 'Total Classes']

    total_classes_per_series['Total Classes'] = 16

    main_teacher_summary = pd.merge(main_teachers, total_classes_per_series, on='Series ID')
    main_teacher_summary['Percentage of Assistance'] = (
        main_teacher_summary['Assigned Classes Count'] / main_teacher_summary['Total Classes']
    ) * 100




    return main_teacher_summary

### Importamos input

In [734]:
start_date = datetime(2026, 1, 12)
series_df = pd.read_csv('new_series.csv')
teacher_availability = pd.read_csv('teacher_availability_matrix.csv')

In [735]:
teacher_availability

,date_period,start_time_period,end_time_period,email_prof,portuguese,spanish,native,recurring_availability,calendar_class,teach_app_series,series_id,c_type,t_type,availability,scheduled_hours,available_hours,occupancy_ratio,class_offering,weekday,hour
0,2025-12-29,05:00:00,06:00:00,j.klawa@slangapp.com,True,False,False,Yes,NaN,NaN,0,NaN,NaN,Yes,NaN,0,NaN,NaN,1,5
1,2026-01-05,05:00:00,06:00:00,j.klawa@slangapp.com,True,False,False,Yes,NaN,NaN,0,NaN,NaN,Yes,NaN,0,NaN,NaN,1,5
2,2026-01-12,05:00:00,06:00:00,j.klawa@slangapp.com,True,False,False,Yes,NaN,NaN,0,NaN,NaN,Yes,NaN,0,NaN,NaN,1,5
3,2026-01-19,05:00:00,06:00:00,j.klawa@slangapp.com,True,False,False,Yes,NaN,NaN,0,NaN,NaN,Yes,NaN,0,NaN,NaN,1,5
4,2026-01-26,05:00:00,06:00:00,j.klawa@slangapp.com,True,False,False,Yes,NaN,NaN,0,NaN,NaN,Yes,NaN,0,NaN,NaN,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69717,2026-06-13,21:00:00,22:00:00,g.vega@slangapp.com,False,True,False,Yes,NaN,NaN,0,NaN,NaN,Yes,NaN,0,NaN,NaN,6,21
69718,2026-06-06,21:00:00,22:00:00,g.vega@slangapp.com,False,True,False,Yes,NaN,NaN,0,NaN,NaN,Yes,NaN,0,NaN,NaN,6,21
69719,2026-06-20,21:00:00,22:00:00,g.vega@slangapp.com,False,True,False,Yes,NaN,NaN,0,NaN,NaN,Yes,NaN,0,NaN,NaN,6,21
69720,2026-06-27,21:00:00,22:00:00,g.vega@slangapp.com,False,True,False,Yes,NaN,NaN,0,NaN,NaN,Yes,NaN,0,NaN,NaN,6,21
69721,2025-12-27,21:00:00,22:00:00,s.paz@slangapp.com,False,True,True,Yes,NaN,NaN,0,NaN,NaN,Yes,NaN,0,NaN,NaN,6,21

In [736]:
teacher_availability = teacher_availability[['email_prof','date_period','start_time_period']]
teacher_availability['slot_time'] =  pd.to_datetime(teacher_availability['date_period'] + ' ' + teacher_availability['start_time_period'])
teacher_availability = teacher_availability[['email_prof', 'slot_time']]
teacher_availability['teacher_email'] = teacher_availability['email_prof']
teacher_availability = teacher_availability[['slot_time', 'teacher_email']]
teacher_availability

/var/folders/_6/jl4t8d4x7hj0k2ct_kt81_3w0000gn/T/ipykernel_27334/3005643807.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teacher_availability['slot_time'] =  pd.to_datetime(teacher_availability['date_period'] + ' ' + teacher_availability['start_time_period'])

                slot_time         teacher_email
0     2025-12-29 05:00:00  j.klawa@slangapp.com
1     2026-01-05 05:00:00  j.klawa@slangapp.com
2     2026-01-12 05:00:00  j.klawa@slangapp.com
3     2026-01-19 05:00:00  j.klawa@slangapp.com
4     2026-01-26 05:00:00  j.klawa@slangapp.com
...                   ...                   ...
69717 2026-06-13 21:00:00   g.vega@slangapp.com
69718 2026-06-06 21:00:00   g.vega@slangapp.com
69719 2026-06-20 21:00:00   g.vega@slangapp.com
69720 2026-06-27 21:00:00   g.vega@slangapp.com
69721 2025-12-27 21:00:00    s.paz@slangapp.com

[69722 rows x 2 columns]

In [737]:
classes = generate_classes(series_df, start_date)
momentos = sorted(list(classes['Starts At'].unique()))
X_c = len(momentos)

In [738]:

teacher_info = pd.read_csv('teachers.csv')
teacher_info.head()

,teacher_email,Level 1,Level 2,Level 3,Level 4,Level 5,Level 6,Level 7,Level 8,Level 9,...,Practice,Premium,Executive,PIT,fee,Type,Tier,Avg Hrs Assigned (Aug–Oct),Current Hours,Max series
0,l.mamani@slangapp.com,False,True,True,True,True,True,True,True,True,...,True,True,True,False,7.0,Part Time,1,100,17,14
1,j.klawa@slangapp.com,True,True,True,True,True,True,True,True,True,...,True,True,True,False,8.0,Part Time,1,124,6,15
2,k.gonzalez@slangapp.com,True,True,True,True,True,True,True,True,True,...,True,True,True,False,8.0,Part Time,1,83,17,14
3,s.rodriguez@slangapp.com,True,True,True,True,True,True,True,True,True,...,True,True,True,False,8.0,Part Time,1,42,0,16
4,m.donato@slangapp.com,True,True,True,True,True,True,True,True,True,...,True,True,True,False,8.0,Part Time,1,42,0,16

In [739]:

teacher_info = teacher_info[['teacher_email', 'Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5', 'Level 6', 'Level 7', 'Level 8', 'Level 9', 'Level 10', 'Level 11', 'Level 12', 'Level 13', 'Level 14', 'Level 15', 'Level 16', 'fee', 'Max series']]
teacher_info['Total series'] = 0
teacher_info['Overachiever'] = False
teacher_info.head()

,teacher_email,Level 1,Level 2,Level 3,Level 4,Level 5,Level 6,Level 7,Level 8,Level 9,...,Level 11,Level 12,Level 13,Level 14,Level 15,Level 16,fee,Max series,Total series,Overachiever
0,l.mamani@slangapp.com,False,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,7.0,14,0,False
1,j.klawa@slangapp.com,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,8.0,15,0,False
2,k.gonzalez@slangapp.com,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,8.0,14,0,False
3,s.rodriguez@slangapp.com,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,8.0,16,0,False
4,m.donato@slangapp.com,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,8.0,16,0,False

In [740]:

# Convert only boolean columns to int
object_dtype_cols = teacher_info.select_dtypes(include='object').columns
#manejamos errores! Valores nulos, etc. 
for col in teacher_info.columns:
    if col not in (['teacher_email', 'fee']):
        teacher_info[col] = teacher_info[col].fillna(False)
        teacher_info[col] = teacher_info[col].astype(int)

start_date = datetime(2026, 1, 12)

In [741]:
teacher_availability.head()

            slot_time         teacher_email
0 2025-12-29 05:00:00  j.klawa@slangapp.com
1 2026-01-05 05:00:00  j.klawa@slangapp.com
2 2026-01-12 05:00:00  j.klawa@slangapp.com
3 2026-01-19 05:00:00  j.klawa@slangapp.com
4 2026-01-26 05:00:00  j.klawa@slangapp.com

In [742]:
teacher_info.tail()

,teacher_email,Level 1,Level 2,Level 3,Level 4,Level 5,Level 6,Level 7,Level 8,Level 9,...,Level 11,Level 12,Level 13,Level 14,Level 15,Level 16,fee,Max series,Total series,Overachiever
61,e.beltran@slangapp.com,0,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,10.5,14,0,0
62,g.vega@slangapp.com,1,1,1,1,1,1,1,1,1,...,1,1,0,0,0,0,10.7,10,0,0
63,c.urrutia@slangapp.com,0,1,1,1,1,1,1,1,1,...,1,0,0,0,0,0,10.8,14,0,0
64,c.ardila@slangapp.com,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,12.0,15,0,0
65,r.caballero@slangapp.com,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,12.0,15,0,0

### Ejecucion

In [743]:
series_df[(series_df['Level Number'].isnull())]

Empty DataFrame
Columns: [Series ID, Series Name, Group ID, New Level, Level Number, Day 1, Day 2, Start Hours (UTC-5), Time 1, Time 2, Start Date, End Date]
Index: []

In [751]:
# series_df = series_df[:50]
assigned_df, unassigned_df, teacher_costs = main(series_df, start_date, teacher_availability, teacher_info, 1, 0.5)
# df, teacher_costs_filtered = main(series_df, start_date, teacher_availability, teacher_info, 1, 0.5) 
# cerca de 2 minutos de ejcucion

Tenemos  66  profesores disponibles para la asignación
Tenemos  624  momentos con una o mas clases
Tenemos  299  series que tenemos que asignar
Hay un total de  4784.0 clases a asignar
Hay un total de  13968.0 horas disponibles de profesores
Hay un total de  17915.0 disponibilidades por nivel
Capa #1
1 ass
2 ass
3 ass
4 ass
5 ass
6 ass
7 ass
{'Online Classes - Tue & Fri - 125', 'Online Classes - Wed & Fri - 138', 'Online Classes - Tue & Wed - 140', 'Online Classes - Wed & Fri - 95', 'Online Classes - Fri & Sat - 11', 'Online Classes - Tue & Wed - 77', 'Online Classes - Mon & Tue - 139'}
Capa #2
Capa #3
8 ass
9 ass
10 ass
11 ass
12 ass
13 ass
14 ass
15 ass
16 ass
17 ass
18 ass
19 ass
20 ass
21 ass
22 ass
23 ass
24 ass
25 ass
26 ass
27 ass
28 ass
29 ass
30 ass
31 ass
32 ass
33 ass
34 ass
35 ass
36 ass
37 ass
38 ass
39 ass
40 ass
41 ass
42 ass
43 ass
44 ass
45 ass
46 ass
47 ass
48 ass
49 ass
50 ass
51 ass
52 ass
53 ass
54 ass
55 ass
56 ass
57 ass
58 ass
59 ass
60 ass
61 ass
62 ass
63 ass
64 ass
65 ass
66 ass
67 ass
68 ass
69 ass
70 ass
71 ass
72 ass
73 ass
74 ass
75 ass
76 ass
77 ass
78 ass
79 ass
80 ass
81 ass
82 ass
83 ass
84 ass
85 ass
86 ass
87 ass
88 ass
89 ass
90 ass
91 ass
92 ass
93 ass
94 ass
95 ass
96 ass
97 ass
98 ass
99 ass
100 ass
101 ass
102 ass
103 ass
104 ass
{'Online Classes - Mon & Thu - 7', 'Online Classes - Thu & Fri - 111', 'Online Classes - Tue & Thu - 122', 'Online Classes - Tue & Thu - 176', 'Online Classes - Mon & Fri - 88', 'Online Classes - Tue & Fri - 208', 'Online Classes - Tue & Thu - 206', 'Online Classes - Tue & Thu - 207', 'Online Classes - Tue & Thu - 224', 'Online Classes - Fri & Sat - 133', 'Online Classes - Tue & Thu - 181', 'Online Classes - Tue & Thu - 148', 'Online Classes - Mon & Tue - 36', 'Online Classes - Tue & Fri - 252', 'Online Classes - Wed & Fri - 14', 'Online Classes - Mon & Wed - 110', 'Online Classes - Mon & Wed - 149', 'Online Classes - Thu & Fri - 194', 'Online Classes - Tue & Thu - 203', 'Online Classes - Fri & Sat - 151', 'Online Classes - Wed & Fri - 198', 'Online Classes - Wed & Fri - 217', 'Online Classes - Tue & Thu - 163', 'Online Classes - Wed & Fri - 9', 'Online Classes - Tue & Thu - 185', 'Online Classes - Mon & Tue - 16', 'Online Classes - Thu & Fri - 112', 'Online Classes - Mon & Tue - 17', 'Online Classes - Mon & Wed - 107', 'Online Classes - Thu & Fri - 154', 'Online Classes - Tue & Wed - 200', 'Online Classes - Thu & Fri - 113', 'Online Classes - Wed & Fri - 13', 'Online Classes - Tue & Sat - 187', 'Online Classes - Mon & Wed - 131', 'Online Classes - Mon & Wed - 129', 'Online Classes - Wed & Thu - 237', 'Online Classes - Tue & Thu - 100', 'Online Classes - Wed & Thu - 212', 'Online Classes - Tue & Thu - 165', 'Online Classes - Wed & Thu - 246', 'Online Classes - Tue & Thu - 177', 'Online Classes - Tue & Thu - 243', 'Online Classes - Mon & Tue - 1', 'Online Classes - Mon & Wed - 275', 'Online Classes - Fri & Sat - 193', 'Online Classes - Tue & Thu - 182', 'Online Classes - Mon & Tue - 119', 'Online Classes - Mon & Wed - 209', 'Online Classes - Tue & Thu - 204', 'Online Classes - Wed & Fri - 157', 'Online Classes - Mon & Tue - 158', 'Online Classes - Mon & Tue - 210', 'Online Classes - Mon & Wed - 127', 'Online Classes - Tue & Wed - 220', 'Online Classes - Tue & Thu - 105', 'Online Classes - Zurich - G15', 'Online Classes - Mon & Fri - 190', 'Online Classes - Tue & Thu - 145', 'Online Classes - Tue & Thu - 147', 'Online Classes - Mon & Wed - 226', 'Online Classes - Tue & Thu - 123', 'Online Classes - Tue & Thu - 166', 'Online Classes - Wed & Fri - 116', 'Online Classes - Tue & Thu - 168', 'Online Classes - Tue & Thu - 101', 'Online Classes - Mon & Wed - 65', 'Online Classes - Tue & Wed - 159', 'Online Classes - Fri & Sat - 27', 'Online Classes - Thu & Fri - 134', 'Online Classes - Tue & Thu - 202', 'Online Classes - Mon & Wed - 25', 'Online Classes - Mon & Fri - 172', 'Online Classes - Tue & Thu - 178', 'Online Classes - Mon & Wed - 109', 'Online Classes - Mon & Tue - 35', 'Online Classes - Tue & Thu - 21', 'Online Classes - Mon & Wed - 170', 'Online Classes - Mon & Wed - 46', 'Online Classes - Tue & Thu - 179', 'Online Classes - Wed & Fri - 155', 'Online Classes - Fri & Sat - 12', 'Online Classes - Mon & Tue - 34', 'Online Classes - Tue & Thu - 121', 'Online Classes - Tue & Thu - 180', 'Online Classes - Mon & Wed - 171', 'Online Classes - Mon & Wed - 128', 'Online Classes - Tue & Thu - 167', 'Online Classes - Tue & Thu - 186', 'Online Classes - Mon & Fri - 191', 'Online Classes - Mon & Wed - 150', 'Online Classes - Tue & Fri - 126', 'Online Classes - Tue & Thu - 164', 'Online Classes - Thu & Fri - 153', 'Online Classes - Mon & Wed - 188', 'Online Classes - Tue & Thu - 143', 'Online Classes - Tue & Wed - 160'}
Capa #4
105 ass
106 ass
107 ass
108 ass
109 ass
110 ass
111 ass
112 ass
113 ass
114 ass
115 ass
116 ass
117 ass
118 ass
119 ass
120 ass
121 ass
122 ass
123 ass
124 ass
125 ass
126 ass
127 ass
128 ass
129 ass
130 ass
131 ass
132 ass
133 ass
134 ass
135 ass
136 ass
137 ass
138 ass
139 ass
140 ass
141 ass
142 ass
143 ass
144 ass
145 ass
146 ass
147 ass
148 ass
149 ass
150 ass
151 ass
152 ass
153 ass
154 ass
155 ass
156 ass
157 ass
158 ass
159 ass
160 ass
161 ass
162 ass
163 ass
164 ass
165 ass
166 ass
167 ass
168 ass
169 ass
170 ass
171 ass
172 ass
{'Online Classes - Mon & Wed - 271', 'Online Classes - Tue & Thu - 242', 'Online Classes - Tue & Thu - 270', 'Online Classes - Tue & Thu - 184', 'Online Classes - Tue & Thu - 98', 'Online Classes - Wed & Fri - 216', 'Online Classes - Tue & Thu - 223', 'Online Classes - Tue & Thu - 102', 'Online Classes - Tue & Thu - 41', 'Online Classes - Tue & Thu - 230', 'Online Classes - Tue & Thu - 272', 'Online Classes - Thu & Fri - 68', 'Online Classes - Fri & Sat - 6', 'Online Classes - Tue & Thu - 22', 'Online Classes - Tue & Thu - 99', 'Online Classes - Mon & Wed - 85', 'Online Classes - Tue & Thu - 262', 'Online Classes - Tue & Thu - 258', 'Online Classes - Tue & Thu - 39', 'Online Classes - Tue & Thu - 183', 'Online Classes - Wed & Fri - 31', 'Online Classes - Wed & Thu - 115', 'Online Classes - Fri & Sat - 152', 'Online Classes - Tue & Thu - 232', 'Online Classes - Wed & Fri - 8', 'Online Classes - Tue & Thu - 233', 'Online Classes - Thu & Fri - 91', 'Online Classes - Mon & Wed - 66', 'Online Classes - Tue & Thu - 144', 'Online Classes - Tue & Thu - 273', 'Online Classes - Tue & Thu - 256', 'Online Classes - Tue & Thu - 43', 'Online Classes - Thu & Fri - 90', 'Online Classes - Wed & Sat - 76', 'Online Classes - Tue & Wed - 162', 'Online Classes - Mon & Wed - 47', 'Online Classes - Wed & Fri - 74', 'Online Classes - Tue & Thu - 251', 'Online Classes - Wed & Fri - 15', 'Online Classes - Mon & Wed - 189', 'Online Classes - Tue & Thu - 142', 'Online Classes - Wed & Thu - 137', 'Online Classes - Tue & Thu - 265', 'Online Classes - Mon & Wed - 257', 'Online Classes - Tue & Thu - 263', 'Online Classes - Wed & Fri - 117', 'Online Classes - Wed & Thu - 114', 'Online Classes - Tue & Thu - 255', 'Online Classes - Tue & Thu - 20', 'Online Classes - Mon & Wed - 108', 'Online Classes - Wed & Fri - 238', 'Online Classes - Tue & Thu - 228', 'Online Classes - Tue & Thu - 23', 'Online Classes - Tue & Thu - 240', 'Online Classes - Tue & Thu - 259', 'Online Classes - Tue & Thu - 250', 'Online Classes - Wed & Fri - 215', 'Online Classes - Tue & Thu - 45', 'Online Classes - Tue & Thu - 278', 'Online Classes - Mon & Wed - 130', 'Online Classes - Tue & Thu - 40', 'Online Classes - Thu & Fri - 92', 'Online Classes - Tue & Thu - 169', 'Online Classes - Thu & Fri - 280', 'Online Classes - Wed & Fri - 32', 'Online Classes - Tue & Thu - 19', 'Online Classes - Tue & Wed - 18', 'Online Classes - Mon & Wed - 235'}
Capa #5
173 ass
174 ass
175 ass
176 ass
177 ass
178 ass
179 ass
180 ass
181 ass
182 ass
183 ass
184 ass
185 ass
186 ass
187 ass
188 ass
189 ass
190 ass
191 ass
192 ass
193 ass
194 ass
195 ass
196 ass
197 ass
198 ass
199 ass
200 ass
201 ass
202 ass
203 ass
204 ass
205 ass
206 ass
207 ass
208 ass
209 ass
210 ass
211 ass
212 ass
213 ass
214 ass
215 ass
216 ass
217 ass
218 ass
{'Online Classes - Mon & Wed - 67', 'Online Classes - Tue & Thu - 225', 'Online Classes - Tue & Thu - 82', 'Online Classes - Mon & Wed - 87', 'Online Classes - Tue & Thu - 120', 'Online Classes - Zurich - G11', 'Online Classes - Wed & Sat - 132', 'Online Classes - Tue & Thu - 58', 'Online Classes - Thu & Sat - 192', 'Online Classes - Tue & Thu - 260', 'Online Classes - Tue & Thu - 205', 'Online Classes - Wed & Fri - 29', 'Online Classes - Tue & Thu - 57', 'Online Classes - Wed & Fri - 196', 'Online Classes - Mon & Wed - 26', 'Online Classes - Wed & Thu - 135', 'Online Classes - Tue & Thu - 79', 'Online Classes - Zurich - G9', 'Online Classes - Wed & Fri - 96', 'Online Classes - Wed & Fri - 51', 'Online Classes - Wed & Fri - 53', 'Online Classes - Mon & Wed - 277', 'Online Classes - Wed & Thu - 136', 'Online Classes - Tue & Thu - 234', 'Online Classes - Wed & Fri - 52', 'Online Classes - Mon & Tue - 276', 'Online Classes - Tue & Wed - 78', 'Online Classes - Wed & Thu - 254', 'Online Classes - Wed & Fri - 73', 'Online Classes - Tue & Wed - 199', 'Online Classes - Tue & Wed - 161', 'Online Classes - Wed & Fri - 71', 'Online Classes - Wed & Fri - 54', 'Online Classes - Zurich - G2', 'Online Classes - Fri & Sat - 211', 'Online Classes - Tue & Thu - 63', 'Online Classes - Tue & Thu - 221', 'Online Classes - Fri & Sat - 173', 'Online Classes - Tue & Fri - 253', 'Online Classes - Wed & Thu - 195', 'Online Classes - Mon & Wed - 86', 'Online Classes - Wed & Thu - 93', 'Online Classes - Tue & Thu - 64', 'Online Classes - Zurich - G1', 'Online Classes - Fri & Sat - 48', 'Online Classes - Tue & Thu - 104'}
Capa #6
219 ass
220 ass
221 ass
222 ass
223 ass
224 ass
225 ass
226 ass
227 ass
228 ass
229 ass
230 ass
231 ass
232 ass
233 ass
234 ass
235 ass
236 ass
237 ass
238 ass
239 ass
240 ass
241 ass
242 ass
243 ass
244 ass
245 ass
246 ass
{'Online Classes - Tue & Wed - 247', 'Online Classes - Zurich - G5', 'Online Classes - Tue & Thu - 2', 'Online Classes - Wed & Fri - 55', 'Online Classes - Tue & Wed - 286', 'Online Classes - Tue & Wed - 218', 'Online Classes - Wed & Fri - 72', 'Online Classes - Zurich - G6', 'Online Classes - Wed & Thu - 245', 'Online Classes - Wed & Fri - 156', 'Online Classes - Wed & Fri - 197', 'Online Classes - Tue & Thu - 283', 'Online Classes - Wed & Fri - 30', 'Online Classes - Tue & Thu - 141', 'Online Classes - Tue & Thu - 274', 'Online Classes - Tue & Thu - 59', 'Online Classes - Tue & Thu - 83', 'Online Classes - Tue & Thu - 174', 'Online Classes - Tue & Thu - 103', 'Online Classes - Tue & Thu - 222', 'Online Classes - Tue & Thu - 229', 'Online Classes - Tue & Fri - 24', 'Online Classes - Tue & Thu - 44', 'Online Classes - Zurich - G13', 'Online Classes - Wed & Fri - 75', 'Online Classes - Tue & Wed - 97', 'Online Classes - Tue & Thu - 60', 'Online Classes - Wed & Fri - 94'}
Capa #7
247 ass
248 ass
249 ass
250 ass
251 ass
252 ass
253 ass
254 ass
255 ass
256 ass
257 ass
258 ass
259 ass
260 ass
261 ass
262 ass
263 ass
264 ass
265 ass
266 ass
267 ass
268 ass
269 ass
270 ass
271 ass
272 ass
273 ass
274 ass
275 ass
276 ass
{'Online Classes - Tue & Wed - 219', 'Online Classes - Tue & Thu - 281', 'Online Classes - Zurich - G12', 'Online Classes - Tue & Thu - 37', 'Online Classes - Wed & Fri - 28', 'Online Classes - Zurich - G10', 'Online Classes - Tue & Thu - 201', 'Online Classes - Wed & Sat - 236', 'Online Classes - Wed & Fri - 214', 'Online Classes - Zurich - G3', 'Online Classes - Tue & Thu - 175', 'Online Classes - Wed & Fri - 282', 'Online Classes - Wed & Fri - 213', 'Online Classes - Tue & Thu - 241', 'Online Classes - Wed & Sat - 118', 'Online Classes - Wed & Fri - 49', 'Online Classes - Tue & Thu - 269', 'Online Classes - Tue & Thu - 266', 'Online Classes - Tue & Thu - 231', 'Online Classes - Zurich - G4', 'Online Classes - Tue & Thu - 239', 'Online Classes - Tue & Wed - 268', 'Online Classes - Tue & Thu - 244', 'Online Classes - Tue & Wed - 261', 'Online Classes - Tue & Thu - 146', 'Online Classes - Tue & Thu - 264', 'Online Classes - Tue & Thu - 249', 'Online Classes - Tue & Thu - 124', 'Online Classes - Zurich - G7', 'Online Classes - Wed & Fri - 227'}
Capa #8
277 ass
278 ass
279 ass
280 ass
281 ass
282 ass
283 ass
284 ass
285 ass
{'Online Classes - Tue & Thu - 61', 'Online Classes - Tue & Thu - 42', 'Online Classes - Tue & Thu - 267', 'Online Classes - Tue & Thu - 38', 'Online Classes - Wed & Fri - 69', 'Online Classes - Wed & Fri - 50', 'Online Classes - Tue & Thu - 84', 'Online Classes - Tue & Thu - 285', 'Online Classes - Tue & Wed - 248'}
Capa #9
Capa #10
Capa #11
286 ass
287 ass
{'Online Classes - Zurich - G14', 'Online Classes - Wed & Fri - 70'}
Solución encontrada. Ahora se va validara la utilidad del resultado!

In [752]:
unassigned_df.to_csv('non_assigned_series.csv')

In [753]:
print('Costo Promedio! $', round(np.mean(assigned_df['Cost']),2))

Costo Promedio! $ 8.83

In [725]:
main_teachers = calculate_main_teacher_assistance(assigned_df)
main_teachers

,Series ID,Teacher,Assigned Classes Count,Total Classes,Percentage of Assistance
0,Online Classes - Fri & Sat - 11,l.mamani@slangapp.com,16,16,100.0
1,Online Classes - Fri & Sat - 12,j.klawa@slangapp.com,16,16,100.0
2,Online Classes - Fri & Sat - 133,j.klawa@slangapp.com,16,16,100.0
3,Online Classes - Fri & Sat - 151,a.jaramillo@slangapp.com,16,16,100.0
4,Online Classes - Fri & Sat - 193,j.klawa@slangapp.com,16,16,100.0
...,...,...,...,...,...
220,Online Classes - Zurich - G3,a.siqueira@slangapp.com,16,16,100.0
221,Online Classes - Zurich - G4,g.vega@slangapp.com,16,16,100.0
222,Online Classes - Zurich - G5,li.ramirez@slangapp.com,16,16,100.0
223,Online Classes - Zurich - G6,c.franco@slangapp.com,16,16,100.0
224,Online Classes - Zurich - G7,h.lizarazo@slangapp.com,16,16,100.0

In [726]:
main_teachers.to_csv('asignaciones_con_PA%.csv') #queremos estar cerca de las 170 series asignadas, ojalá :pray:

In [727]:
len(main_teachers)

225